### ISSUE TITLE
One accordion opened at once.

### ISSUE THREAD

**Issue by rikbonhof** [coolc0ders/Accordion-View-Xamarin.Forms#1]
Is there an option to have only one accordion opened at once? So if item 1 is opened and you tap item 2, 1 will close and 2 will open.

Also it would be nice if the first item would be opened by default. Sadly I did not manage to do this from code.

**Comment by DamienDoumer** [comment]
Hi @rikbonhof  this control does not have the options you just described. Cause it is designed to be a single control which just serves as template for the collection view. 
But, you could implement the functionality you are talking about by binding the IsOpened property of the accordion view with a property of the data it represents inside the collection, and manipulate those bindings to implement the scenario you are talking about.
